#!/usr/bin/perl
use strict; use warnings;
use Getopt::Long qw(GetOptions);
Getopt::Long::Configure qw(gnu_getopt);
use Perl::Dist::APPerl;

my $usage = <<'END_USAGE';
apperl-init [-h|--help] [-p|--perlrepo <path>] [-c|--cosmorepo <path>]
  -p|--perlrepo     Set path to perl repo (Skips creating perl repo, git fetch, etc)
  -c|--cosmorepo    Set path to cosmopolitan repo (Skips creating cosmo repo, git fetch, etc)
  -n|--no-project   Skip creating apperl-project.json in the current directory
  -h|--help         Show this message
Initialize APPerl tools, Create an APPerl project or reinitialize an existing one
END_USAGE
my $perlrepo;
my $cosmorepo;
my $help;
my $noproject;
GetOptions("perlrepo|p=s" => \$perlrepo,
           "cosmorepo|c=s" => \$cosmorepo,
           "help|h" => \$help,
           "no-project|n" => \$noproject
) or die($usage);
if($help) {
    print $usage;
    exit 0;
}

Perl::Dist::APPerl::Init($perlrepo, $cosmorepo, $noproject);
