#!/usr/bin/perl
use strict; use warnings;
use Getopt::Long qw(GetOptions);
Getopt::Long::Configure qw(gnu_getopt);
use Perl::Dist::APPerl;

my $usage = <<'END_USAGE';
apperl-new-config [-h|--help] [-n|--name <name>] [-b|--base <base>]
  -n|--name     name of the default config
  -b|--base     base class of the config
  -h|--help     Show this message
Create a new APPerl config and add it to the project
END_USAGE
my $name;
my $base;
my $help;
GetOptions("name|n=s" => \$name,
           "base|b=s" => \$base,
           "help|h" => \$help,
) or die($usage);
if($help) {
    print $usage;
    exit 0;
}

Perl::Dist::APPerl::NewConfig($name, $base);
