
# GitHub Actions CI script for Perl-Dist-APPerl
# (C) 2022 Gavin Hayes

name: Build Actually Portable Perl
on:   [ push, pull_request ]

jobs:
  build-linux:
    name:    Build Perl-Dist-APPerl
    runs-on: ubuntu-latest
    steps:
    - name: Fetch repo
      uses: actions/checkout@v7
      with:
        path: 'Perl-Dist-APPerl'
    - name: Install Perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.42'
        install-modules-with: cpanm
        install-modules: File::ShareDir::Install
    - name: Test in-tree
      run: |
        cd Perl-Dist-APPerl
        prove -lv t
    - name: Build Perl-Dist-APPerl release
      run: |
        cd Perl-Dist-APPerl
        perl Makefile.PL
        make manifest
        make dist
        mv Perl-Dist-APPerl-v*.tar.gz ../
    - name: Upload build artifacts
      uses: actions/upload-artifact@v7
      with:
        name: cpan
        if-no-files-found: error
        path: Perl-Dist-APPerl-v*.tar.gz
        archive: false

  build-apperl:
    name:    Build perl.com
    runs-on: ubuntu-latest
    needs:   build-linux
    strategy:
      matrix:
        config: [full, small, aarch64-full, aarch64-small, full-536, small-536, full-540, small-540, full-542, small-542]
    steps:
    - name: Fetch build artifacts
      uses: actions/download-artifact@v8
    - name: prepare for installing module
      run: |
        mv Perl-Dist-APPerl-v*.tar.gz Perl-Dist-APPerl.tar.gz
    - name: Install Perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.42'
        install-modules-with: cpanm
        install-modules: Perl-Dist-APPerl.tar.gz
    - name: Get Latest Successful Cosmopolitan Run ID
      if: ${{ matrix.config == 'full' ||  matrix.config == 'small' || matrix.config == 'aarch64-full' ||  matrix.config == 'aarch64-small'}}
      env:
        GH_TOKEN: ${{ secrets.COSMOPOLITAN_TOKEN }}
      run: |
        RUN_ID=$(gh run list --repo jart/cosmopolitan --workflow "nightly-cosmocc.yml" --status success --limit 1 --json databaseId --jq '.[0].databaseId')
        echo "COSMO_RUN_ID=$RUN_ID" >> $GITHUB_ENV
    - name: Fetch cosmocc
      if: ${{ matrix.config == 'full' ||  matrix.config == 'small' || matrix.config == 'aarch64-full' ||  matrix.config == 'aarch64-small'}}
      uses: actions/download-artifact@v8
      with:
        repository: 'jart/cosmopolitan'
        github-token: ${{ secrets.COSMOPOLITAN_TOKEN}}
        run-id: ${{ env.COSMO_RUN_ID }}
        name: 'cosmocc'
        skip-decompress: true
    - name: Setup cosmocc
      if: ${{ matrix.config == 'full' ||  matrix.config == 'small' || matrix.config == 'aarch64-full' ||  matrix.config == 'aarch64-small'}}
      run: |
        mkdir -p ~/.local/share/apperl/cosmocc-head
        mv cosmocc.zip ~/.local/share/apperl/cosmocc-head
        cd ~/.local/share/apperl/cosmocc-head
        unzip cosmocc.zip
        ls -la /home/runner/.local/share/apperl/cosmocc-head/bin/
        mkdir -p ~/.config/apperl
        echo '{"cosmocc-head" : "/home/runner/.local/share/apperl/cosmocc-head"}' > ~/.config/apperl/site.json
    - name: Prepare to run AARCH64 binaries
      if: ${{ matrix.config == 'aarch64-full' ||  matrix.config == 'aarch64-small'}}
      run: |
        sudo apt update
        sudo apt install qemu-user-static binfmt-support
    - name: Load config
      run: |
          DEST_BIN=$(apperlm get-config-key ${{ matrix.config }} dest) && echo "DEST_BIN=$DEST_BIN" >> $GITHUB_ENV
          REL_NAME=APPerl-$(perl -MPerl::Dist::APPerl -e 'print $Perl::Dist::APPerl::VERSION')-${{ matrix.config }}.zip && echo "REL_NAME=$REL_NAME" >> $GITHUB_ENV
    - name: support ape bins
      run: sudo sh -c "echo ':APE:M::MZqFpD::/bin/sh:' >/proc/sys/fs/binfmt_misc/register"
    - name: Configure and Build perl.com
      env:
        CF_BY: ${{ secrets.CF_BY }}
        CF_EMAIL: ${{ secrets.CF_EMAIL }}
      run: |
        ls -la
        apperlm init --name ${{ matrix.config }}
        apperlm list
        apperlm configure -Dcf_by="$CF_BY" -Dcf_email="$CF_EMAIL"
        apperlm build
        zip -r ${{ env.REL_NAME }} ${{ env.DEST_BIN }} ${{ env.DEST_BIN }}.dbg
    - name: Run make test
      run: |
        dir=$(jq -r --arg cfg "${{ matrix.config }}" '.configs[$cfg].perl_build_dir' .apperl/user-project.json)
        echo "$dir"
        make -C $dir test 2>&1 | tee ${{ matrix.config }}-make-test.log
    - name: Upload build artifacts
      uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.config }}
        if-no-files-found: error
        path: |
          ${{ env.DEST_BIN }}
          ${{ env.DEST_BIN }}.dbg
          ${{ env.REL_NAME }}
          ${{ matrix.config }}-make-test.log

  test-Perl-Dist-APPerl:
    name:    test Perl-Dist-APPerl
    runs-on: ubuntu-latest
    needs:   build-apperl
    strategy:
      matrix:
        version: ['5.10', '5.36', '5.38', '5.40', '5.42']
    steps:
    - name: Fetch repo
      uses: actions/checkout@v7
      with:
        path: 'Perl-Dist-APPerl'
    - name: Install Perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.version }}
        install-modules-with: cpanm
        install-modules: B::Keywords HTTP::Tiny Test::Pod::LinkCheck::Lite
    - name: download build artifacts
      uses: actions/download-artifact@v8
      with:
        merge-multiple: true
    - name: Setup for tests
      run: |
        cd Perl-Dist-APPerl
        cpanm --installdeps --notest .
        mv ../*.com* ./
        chmod +x perl.com
        sudo sh -c "echo ':APE:M::MZqFpD::/bin/sh:' >/proc/sys/fs/binfmt_misc/register"
    - name: Run tests
      run: |
        cd Perl-Dist-APPerl
        perl Makefile.PL
        make
        make authortest
    - name: Archive CPAN logs
      if: ${{ failure() }}
      uses: actions/upload-artifact@v7
      with:
        name: cpan_log
        path: /home/runner/.cpanm/work/*/build.log

  test-nobuild-builds:
    name:    Test building nobuild configs
    needs:   build-apperl
    strategy:
      matrix:
        os: [ubuntu-latest] #, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Fetch build artifacts
      uses: actions/download-artifact@v8
      with:
        merge-multiple: true
    - name: support ape bins
      run: sudo sh -c "echo ':APE:M::MZqFpD::/bin/sh:' >/proc/sys/fs/binfmt_misc/register"
    - name: Try nobuild build
      run: |
        mkdir src
        cp perl.com src/
        chmod +x src/perl.com
        src/perl.com /zip/bin/apperlm list

  create-release:
    name:    Create release
    runs-on: ubuntu-latest
    needs:   [ build-linux, build-apperl, test-Perl-Dist-APPerl, test-nobuild-builds ]
    steps:
    - name: Fetch build artifacts
      if:   ${{ github.ref_type == 'tag' }}
      uses: actions/download-artifact@v8
    - name: Build binary amalgamation for uploading to microsoft
      if:   ${{ github.ref_type == 'tag' }}
      run: |
        sudo sh -c "echo ':APE:M::MZqFpD::/bin/sh:' >/proc/sys/fs/binfmt_misc/register"
        chmod +x full/perl.com
        REL_NAME=APPerl-$(full/perl.com -MPerl::Dist::APPerl -e 'print $Perl::Dist::APPerl::VERSION')-all.zip
        zip -r $REL_NAME */*.com*
    - name: Publish release
      if:   ${{ github.ref_type == 'tag' }}
      uses: softprops/action-gh-release@v1
      with:
        fail_on_unmatched_files: true
        draft: true
        files: |
          Perl-Dist-APPerl-v*.tar.gz/Perl-Dist-APPerl-v*.tar.gz
          full/*
          small/*
          aarch64-full/*
          aarch64-small/*
          full-536/*
          small-536/*
          full-540/*
          small-540/*
          full-542/*
          small-542/*
          APPerl-*-all.zip
