
# GitHub Actions CI script for Perl-Dist-APPerl
# (C) 2022 Gavin Hayes

name: Build Actually Portable Perl
on:   [ push, pull_request ]

jobs:
  build-linux:
    name:    Build Perl-Dist-APPerl
    runs-on: ubuntu-latest
    steps:
    - name: Fetch repo and submodules
      uses: actions/checkout@v3
      with:
        path: 'Perl-Dist-APPerl'
    - name: Install Perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.36'
    - name: Test in-tree
      run: |
        cd Perl-Dist-APPerl
        prove -lv t
    - name: Build Perl-Dist-APPerl release
      run: |
        cd Perl-Dist-APPerl
        perl Makefile.PL
        make manifest
        make dist
        mv Perl-Dist-APPerl-v*.tar.gz ../
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: cpan
        if-no-files-found: error
        path: Perl-Dist-APPerl-v*.tar.gz

  build-apperl:
    name:    Build perl.com
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [{name: apperl, perl-ref: cosmo, cosmo-repo: 'jart/cosmopolitan', cosmo-ref: master }, {name: 'apperl-vista', perl-ref: 'cosmo-vista', cosmo-repo: 'G4Vi/cosmopolitan', cosmo-ref: fix_vista_via_revert  }]
    steps:
    - name: Fetch Perl fork
      uses: actions/checkout@v3
      with:
        repository: 'G4Vi/perl5'
        ref: ${{ matrix.config.perl-ref }}
        path: 'perl5'
    - name: Fetch cosmopolitan
      uses: actions/checkout@v3
      with:
        repository: ${{ matrix.config.cosmo-repo }}
        ref: ${{ matrix.config.cosmo-ref }}
        path: 'cosmopolitan'
    - name: support ape bins
      run: sudo sh -c "echo ':APE:M::MZqFpD::/bin/sh:' >/proc/sys/fs/binfmt_misc/register"
    - name: Configure and Build Perl
      run: |
        cd perl5
        cosmo/superConfigure -de
        make
        cosmo/buildAPPerl.sh
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.config.name }}
        if-no-files-found: error
        path: perl5/cosmo/o/perl.com

  create-release:
    name:    Create release
    runs-on: ubuntu-latest
    needs:   [ build-linux, build-apperl ]
    steps:
    - name: Fetch build artifacts
      if:   ${{ github.ref_type == 'tag' }}
      uses: actions/download-artifact@v3
    - name: Publish release
      if:   ${{ github.ref_type == 'tag' }}
      uses: softprops/action-gh-release@v1
      with:
        fail_on_unmatched_files: true
        draft: true
        files: |
          cpan/Perl-Dist-APPerl-v*.tar.gz
          apperl/perl.com
          apperl-vista/perl.com
