
# GitHub Actions CI script for Perl-Dist-APPerl
# (C) 2022 Gavin Hayes

name: Build Actually Portable Perl
on:   [ push, pull_request ]

jobs:
  build-linux:
    name:    Build Perl-Dist-APPerl
    runs-on: ubuntu-latest
    steps:
    - name: Fetch repo and submodules
      uses: actions/checkout@v3
      with:
        path: 'Perl-Dist-APPerl'
    - name: Install Perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.36'
    - name: Test in-tree
      run: |
        cd Perl-Dist-APPerl
        prove -lv t
    - name: Build Perl-Dist-APPerl release
      run: |
        cd Perl-Dist-APPerl
        perl Makefile.PL
        make manifest
        make dist
        mv Perl-Dist-APPerl-v*.tar.gz ../
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: cpan
        if-no-files-found: error
        path: Perl-Dist-APPerl-v*.tar.gz

  build-apperl:
    name:    Build perl.com
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [{name: apperl, perl-ref: cosmo-apperl, cosmo-repo: 'jart/cosmopolitan', cosmo-ref: master, apperl-config: v5.36.0-full }, {name: 'apperl-vista', perl-ref: 'cosmo-apperl-vista', cosmo-repo: 'G4Vi/cosmopolitan', cosmo-ref: fix_vista_via_revert, apperl-config: v5.36.0-full-vista  }]
    steps:
    - name: Fetch Perl fork
      uses: actions/checkout@v3
      with:
        repository: 'G4Vi/perl5'
        ref: ${{ matrix.config.perl-ref }}
        path: 'perl5'
    - name: Fetch cosmopolitan
      uses: actions/checkout@v3
      with:
        repository: ${{ matrix.config.cosmo-repo }}
        ref: ${{ matrix.config.cosmo-ref }}
        path: 'cosmopolitan'
    - name: support ape bins
      run: sudo sh -c "echo ':APE:M::MZqFpD::/bin/sh:' >/proc/sys/fs/binfmt_misc/register"
    - name: Fetch build artifacts
      uses: actions/download-artifact@v3
    - name: prepare for installing module
      run: |
        mv cpan/Perl-Dist-APPerl-v*.tar.gz Perl-Dist-APPerl.tar.gz
    - name: Install Perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.36'
        install-modules-with: cpanm
        install-modules: Perl-Dist-APPerl.tar.gz
    - name: Configure and Build perl.com
      env:
        CF_BY: ${{ secrets.CF_BY }}
        CF_EMAIL: ${{ secrets.CF_EMAIL }}
      run: |
        ls -la
        apperl-init -p perl5 -c cosmopolitan
        apperl-set ${{ matrix.config.apperl-config }}
        apperl-list
        apperl-configure -Dcf_by="$CF_BY" -Dcf_email="$CF_EMAIL"
        apperl-build
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.config.name }}
        if-no-files-found: error
        path: ~/.config/apperl/o/${{ matrix.config.apperl-config }}/perl.com

  create-release:
    name:    Create release
    runs-on: ubuntu-latest
    needs:   [ build-linux, build-apperl ]
    steps:
    - name: Fetch build artifacts
      if:   ${{ github.ref_type == 'tag' }}
      uses: actions/download-artifact@v3
    - name: Publish release
      if:   ${{ github.ref_type == 'tag' }}
      uses: softprops/action-gh-release@v1
      with:
        fail_on_unmatched_files: true
        draft: true
        files: |
          cpan/Perl-Dist-APPerl-v*.tar.gz
          apperl/perl.com
          apperl-vista/perl.com
